### ISSUE TITLE
Error in __repr__ method of Monitor class

### ISSUE THREAD

**Issue by c-buzz** [ZoneMinder/pyzm#51]
The environment is the following:
```
- Ubuntu 22.04.4 LTS
- ZoneMinder v1.36.34
- ZoneMinder API 2.0
- zm-py version 0.5.2
- Python 3.10.12
```
The following code has been used to get a list of `Monitor`:
```
import zoneminder
from zoneminder.zm import ZoneMinder

zm_client = ZoneMinder(host, user, pwd, server_path="", verify_ssl=True)

res = zm_client.login()

if res:
    monitors = zm_client.get_monitors()
    for monitor in monitors:
        print(monitor)
```

The error returned:

```
Traceback (most recent call last):
  File "/home/myuser/workspace/zm-plugins/convert_frames_to_files.py", line 25, in <module>
    print(monitor)
  File "/home/myuser/workspace/zm-plugins/.venv/lib/python3.10/site-packages/zoneminder/monitor.py", line 108, in __str__
    return self.__repr__()
  File "/home/myuser/workspace/zm-plugins/.venv/lib/python3.10/site-packages/zoneminder/monitor.py", line 104, in __repr__
    return self._fmt.format(self.__class__.__name__, self.id, self.name)
IndexError: Replacement index 3 out of range for positional args tuple
```

If I forgot any extra useful info, let me know.

**Comment by c-buzz** [comment]
Just confused library. Sorry
